// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAXDdN2Nj5fCvzsVSWts53IjGdhf50bBE',
    appId: '1:112492983786:web:c2f0a0395be79107382e93',
    messagingSenderId: '112492983786',
    projectId: 'flutter-app-4cf33',
    authDomain: 'flutter-app-4cf33.firebaseapp.com',
    storageBucket: 'flutter-app-4cf33.appspot.com',
    measurementId: 'G-DMG0YVG7H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJzrZ7P8ono8GFCJiiZ2dbzdKWvsCmbSc',
    appId: '1:112492983786:android:a27dc776742df5fc382e93',
    messagingSenderId: '112492983786',
    projectId: 'flutter-app-4cf33',
    storageBucket: 'flutter-app-4cf33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYiZ8Zr4n5rrvQMRReqfjoJyNWiOwdjzw',
    appId: '1:112492983786:ios:8bc95fe9f732b141382e93',
    messagingSenderId: '112492983786',
    projectId: 'flutter-app-4cf33',
    storageBucket: 'flutter-app-4cf33.appspot.com',
    iosClientId: '112492983786-l99jvrqvjh64amqkvh5484k8nq8m2n48.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYiZ8Zr4n5rrvQMRReqfjoJyNWiOwdjzw',
    appId: '1:112492983786:ios:8bc95fe9f732b141382e93',
    messagingSenderId: '112492983786',
    projectId: 'flutter-app-4cf33',
    storageBucket: 'flutter-app-4cf33.appspot.com',
    iosClientId: '112492983786-l99jvrqvjh64amqkvh5484k8nq8m2n48.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingFlutter',
  );
}
